### PR TITLE
Remove superfluous quotation mark

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-1

### CODE REVIEW

**Comment by takluyver** [comment]
Tested this locally, it seems to work for me

**Comment by Carreau** [comment]
:-)

**Comment by Carreau** [comment]
The `dist_info` file also need to be removed even when using --symlink.

**Comment by takluyver** [comment]
From site_packages? That's odd, it shouldn't need to be.

**Comment by takluyver** [comment]
It replaces it correctly for me. If you have changed the version number since doing `flit install --symlink` before, though, you'll be left with two `.dist-info` directories, and I don't know which it will pick.

**Comment by Carreau** [comment]
hum... I'll recheck.

**Pull request merged**
